/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query fetchBoardHomework10Detail($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n    }\n  }\n": typeof types.FetchBoardHomework10DetailDocument,
    "\n  query fetchBoardsHomework10($page: Int) {\n    fetchBoards(page: $page) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n": typeof types.FetchBoardsHomework10Document,
    "\n  mutation deleteBoardHomework10($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n": typeof types.DeleteBoardHomework10Document,
    "\n  mutation loginUser($email: String!, $password: String!) {\n    loginUser(email: $email, password: $password) {\n      accessToken\n    }\n  }\n": typeof types.LoginUserDocument,
    "\n  mutation createUser($createUserInput: CreateUserInput!) {\n    createUser(createUserInput: $createUserInput) {\n      _id\n      email\n      name\n    }\n  }\n": typeof types.CreateUserDocument,
    "\n  mutation createBoard7(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n": typeof types.CreateBoard7Document,
    "\n  query fetchBoardHomework8($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n    }\n  }\n": typeof types.FetchBoardHomework8Document,
    "\n  mutation createBoard8(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n": typeof types.CreateBoard8Document,
    "\n  query fetchBoardHomework9Detail($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n    }\n  }\n": typeof types.FetchBoardHomework9DetailDocument,
    "\n  mutation createBoard9(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n": typeof types.CreateBoard9Document,
    "\n  query fetchBoardsHomework9($page: Int) {\n    fetchBoards(page: $page) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n": typeof types.FetchBoardsHomework9Document,
    "\n  mutation deleteBoardHomework9($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n": typeof types.DeleteBoardHomework9Document,
    "\n  mutation restoreAccessToken {\n    restoreAccessToken {\n      accessToken\n    }\n  }\n": typeof types.RestoreAccessTokenDocument,
    "\n  query FetchBoardComments($page: Int, $boardId: ID!) {\n    fetchBoardComments(page: $page, boardId: $boardId) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n": typeof types.FetchBoardCommentsDocument,
    "\n  mutation createBoardComment(\n    $createBoardCommentInput: CreateBoardCommentInput!\n    $boardId: ID!\n  ) {\n    createBoardComment(\n      createBoardCommentInput: $createBoardCommentInput\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n": typeof types.CreateBoardCommentDocument,
    "\n  mutation updateBoardComment(\n    $updateBoardCommentInput: UpdateBoardCommentInput!\n    $password: String\n    $boardCommentId: ID!\n  ) {\n    updateBoardComment(\n      updateBoardCommentInput: $updateBoardCommentInput\n      password: $password\n      boardCommentId: $boardCommentId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n": typeof types.UpdateBoardCommentDocument,
    "\n  query fetchBoard($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n    }\n  }\n": typeof types.FetchBoardDocument,
    "\n  query fetchBoardLegacyDetail($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n    }\n  }\n": typeof types.FetchBoardLegacyDetailDocument,
    "\n  query fetchBoards(\n    $page: Int\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoards(\n      page: $page\n      search: $search\n      startDate: $startDate\n      endDate: $endDate\n    ) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n": typeof types.FetchBoardsDocument,
    "\n  mutation deleteBoard($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n": typeof types.DeleteBoardDocument,
    "\n  query fetchBoardsCount(\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoardsCount(search: $search, startDate: $startDate, endDate: $endDate)\n  }\n": typeof types.FetchBoardsCountDocument,
    "\n  query fetchBoardsLegacyList($page: Int) {\n    fetchBoards(page: $page) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n": typeof types.FetchBoardsLegacyListDocument,
    "\n  mutation deleteBoardLegacyList($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n": typeof types.DeleteBoardLegacyListDocument,
    "\n  mutation createBoard(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n    $youtubeUrl: String\n    $boardAddress: BoardAddressInput\n    $images: [String!]\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n        youtubeUrl: $youtubeUrl\n        boardAddress: $boardAddress\n        images: $images\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n      youtubeUrl\n      images\n    }\n  }\n": typeof types.CreateBoardDocument,
    "\n  query fetchBoardWrite($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n    }\n  }\n": typeof types.FetchBoardWriteDocument,
    "\n  mutation updateBoard(\n    $updateBoardInput: UpdateBoardInput!\n    $password: String\n    $boardId: ID!\n  ) {\n    updateBoard(\n      updateBoardInput: $updateBoardInput\n      password: $password\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n": typeof types.UpdateBoardDocument,
    "\n  mutation uploadBoardFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n      _id\n      size\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UploadBoardFileDocument,
    "\n  mutation createTravelproductQuestionAnswer(\n    $createTravelproductQuestionAnswerInput: CreateTravelproductQuestionAnswerInput!\n    $travelproductQuestionId: ID!\n  ) {\n    createTravelproductQuestionAnswer(\n      createTravelproductQuestionAnswerInput: $createTravelproductQuestionAnswerInput\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": typeof types.CreateTravelproductQuestionAnswerDocument,
    "\n  query fetchTravelproductQuestionAnswersForList(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": typeof types.FetchTravelproductQuestionAnswersForListDocument,
    "\n  mutation updateTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n    $updateTravelproductQuestionAnswerInput: UpdateTravelproductQuestionAnswerInput!\n  ) {\n    updateTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n      updateTravelproductQuestionAnswerInput: $updateTravelproductQuestionAnswerInput\n    ) {\n      _id\n      contents\n    }\n  }\n": typeof types.UpdateTravelproductQuestionAnswerDocument,
    "\n  query fetchTravelproductQuestionAnswersForReply(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": typeof types.FetchTravelproductQuestionAnswersForReplyDocument,
    "\n  mutation deleteTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n  ) {\n    deleteTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n    )\n  }\n": typeof types.DeleteTravelproductQuestionAnswerDocument,
    "\n  mutation createTravelproductQuestion(\n    $createTravelproductQuestionInput: CreateTravelproductQuestionInput!\n    $travelproductId: ID!\n  ) {\n    createTravelproductQuestion(\n      createTravelproductQuestionInput: $createTravelproductQuestionInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": typeof types.CreateTravelproductQuestionDocument,
    "\n  query fetchTravelproductQuestions($page: Int, $travelproductId: ID!) {\n    fetchTravelproductQuestions(\n      page: $page\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": typeof types.FetchTravelproductQuestionsDocument,
    "\n  query fetchTravelproductForDetail($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      price\n      contents\n      images\n      tags\n      pickedCount\n      travelproductAddress {\n        address\n        addressDetail\n        lat\n        lng\n      }\n      buyer {\n        _id\n        name\n        email\n      }\n      seller {\n        _id\n        name\n        email\n      }\n    }\n  }\n": typeof types.FetchTravelproductForDetailDocument,
    "\n  query fetchUserLoggedIn {\n    fetchUserLoggedIn {\n      _id\n      email\n      name\n      userPoint {\n        _id\n        amount\n      }\n    }\n  }\n": typeof types.FetchUserLoggedInDocument,
    "\n  mutation deleteTravelproductQuestion($travelproductQuestionId: ID!) {\n    deleteTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n    )\n  }\n": typeof types.DeleteTravelproductQuestionDocument,
    "\n  mutation updateTravelproductQuestion(\n    $travelproductQuestionId: ID!\n    $updateTravelproductQuestionInput: UpdateTravelproductQuestionInput!\n  ) {\n    updateTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n      updateTravelproductQuestionInput: $updateTravelproductQuestionInput\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": typeof types.UpdateTravelproductQuestionDocument,
    "\n  mutation toggleTravelproductPick($travelproductId: ID!) {\n    toggleTravelproductPick(travelproductId: $travelproductId)\n  }\n": typeof types.ToggleTravelproductPickDocument,
    "\n  mutation createPointTransactionOfBuyingAndSelling($useritemId: ID!) {\n    createPointTransactionOfBuyingAndSelling(useritemId: $useritemId) {\n      _id\n    }\n  }\n": typeof types.CreatePointTransactionOfBuyingAndSellingDocument,
    "\n  mutation createTravelproduct(\n    $createTravelproductInput: CreateTravelproductInput!\n  ) {\n    createTravelproduct(createTravelproductInput: $createTravelproductInput) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n": typeof types.CreateTravelproductDocument,
    "\n  mutation updateTravelproduct(\n    $updateTravelproductInput: UpdateTravelproductInput!\n    $travelproductId: ID!\n  ) {\n    updateTravelproduct(\n      updateTravelproductInput: $updateTravelproductInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n": typeof types.UpdateTravelproductDocument,
    "\n  mutation uploadTravelproductFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n    }\n  }\n": typeof types.UploadTravelproductFileDocument,
    "\n  query fetchTravelproductForEdit($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n": typeof types.FetchTravelproductForEditDocument,
};
const documents: Documents = {
    "\n  query fetchBoardHomework10Detail($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n    }\n  }\n": types.FetchBoardHomework10DetailDocument,
    "\n  query fetchBoardsHomework10($page: Int) {\n    fetchBoards(page: $page) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n": types.FetchBoardsHomework10Document,
    "\n  mutation deleteBoardHomework10($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n": types.DeleteBoardHomework10Document,
    "\n  mutation loginUser($email: String!, $password: String!) {\n    loginUser(email: $email, password: $password) {\n      accessToken\n    }\n  }\n": types.LoginUserDocument,
    "\n  mutation createUser($createUserInput: CreateUserInput!) {\n    createUser(createUserInput: $createUserInput) {\n      _id\n      email\n      name\n    }\n  }\n": types.CreateUserDocument,
    "\n  mutation createBoard7(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n": types.CreateBoard7Document,
    "\n  query fetchBoardHomework8($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n    }\n  }\n": types.FetchBoardHomework8Document,
    "\n  mutation createBoard8(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n": types.CreateBoard8Document,
    "\n  query fetchBoardHomework9Detail($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n    }\n  }\n": types.FetchBoardHomework9DetailDocument,
    "\n  mutation createBoard9(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n": types.CreateBoard9Document,
    "\n  query fetchBoardsHomework9($page: Int) {\n    fetchBoards(page: $page) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n": types.FetchBoardsHomework9Document,
    "\n  mutation deleteBoardHomework9($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n": types.DeleteBoardHomework9Document,
    "\n  mutation restoreAccessToken {\n    restoreAccessToken {\n      accessToken\n    }\n  }\n": types.RestoreAccessTokenDocument,
    "\n  query FetchBoardComments($page: Int, $boardId: ID!) {\n    fetchBoardComments(page: $page, boardId: $boardId) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n": types.FetchBoardCommentsDocument,
    "\n  mutation createBoardComment(\n    $createBoardCommentInput: CreateBoardCommentInput!\n    $boardId: ID!\n  ) {\n    createBoardComment(\n      createBoardCommentInput: $createBoardCommentInput\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n": types.CreateBoardCommentDocument,
    "\n  mutation updateBoardComment(\n    $updateBoardCommentInput: UpdateBoardCommentInput!\n    $password: String\n    $boardCommentId: ID!\n  ) {\n    updateBoardComment(\n      updateBoardCommentInput: $updateBoardCommentInput\n      password: $password\n      boardCommentId: $boardCommentId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n": types.UpdateBoardCommentDocument,
    "\n  query fetchBoard($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n    }\n  }\n": types.FetchBoardDocument,
    "\n  query fetchBoardLegacyDetail($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n    }\n  }\n": types.FetchBoardLegacyDetailDocument,
    "\n  query fetchBoards(\n    $page: Int\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoards(\n      page: $page\n      search: $search\n      startDate: $startDate\n      endDate: $endDate\n    ) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n": types.FetchBoardsDocument,
    "\n  mutation deleteBoard($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n": types.DeleteBoardDocument,
    "\n  query fetchBoardsCount(\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoardsCount(search: $search, startDate: $startDate, endDate: $endDate)\n  }\n": types.FetchBoardsCountDocument,
    "\n  query fetchBoardsLegacyList($page: Int) {\n    fetchBoards(page: $page) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n": types.FetchBoardsLegacyListDocument,
    "\n  mutation deleteBoardLegacyList($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n": types.DeleteBoardLegacyListDocument,
    "\n  mutation createBoard(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n    $youtubeUrl: String\n    $boardAddress: BoardAddressInput\n    $images: [String!]\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n        youtubeUrl: $youtubeUrl\n        boardAddress: $boardAddress\n        images: $images\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n      youtubeUrl\n      images\n    }\n  }\n": types.CreateBoardDocument,
    "\n  query fetchBoardWrite($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n    }\n  }\n": types.FetchBoardWriteDocument,
    "\n  mutation updateBoard(\n    $updateBoardInput: UpdateBoardInput!\n    $password: String\n    $boardId: ID!\n  ) {\n    updateBoard(\n      updateBoardInput: $updateBoardInput\n      password: $password\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n": types.UpdateBoardDocument,
    "\n  mutation uploadBoardFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n      _id\n      size\n      createdAt\n      updatedAt\n    }\n  }\n": types.UploadBoardFileDocument,
    "\n  mutation createTravelproductQuestionAnswer(\n    $createTravelproductQuestionAnswerInput: CreateTravelproductQuestionAnswerInput!\n    $travelproductQuestionId: ID!\n  ) {\n    createTravelproductQuestionAnswer(\n      createTravelproductQuestionAnswerInput: $createTravelproductQuestionAnswerInput\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": types.CreateTravelproductQuestionAnswerDocument,
    "\n  query fetchTravelproductQuestionAnswersForList(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": types.FetchTravelproductQuestionAnswersForListDocument,
    "\n  mutation updateTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n    $updateTravelproductQuestionAnswerInput: UpdateTravelproductQuestionAnswerInput!\n  ) {\n    updateTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n      updateTravelproductQuestionAnswerInput: $updateTravelproductQuestionAnswerInput\n    ) {\n      _id\n      contents\n    }\n  }\n": types.UpdateTravelproductQuestionAnswerDocument,
    "\n  query fetchTravelproductQuestionAnswersForReply(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": types.FetchTravelproductQuestionAnswersForReplyDocument,
    "\n  mutation deleteTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n  ) {\n    deleteTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n    )\n  }\n": types.DeleteTravelproductQuestionAnswerDocument,
    "\n  mutation createTravelproductQuestion(\n    $createTravelproductQuestionInput: CreateTravelproductQuestionInput!\n    $travelproductId: ID!\n  ) {\n    createTravelproductQuestion(\n      createTravelproductQuestionInput: $createTravelproductQuestionInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": types.CreateTravelproductQuestionDocument,
    "\n  query fetchTravelproductQuestions($page: Int, $travelproductId: ID!) {\n    fetchTravelproductQuestions(\n      page: $page\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": types.FetchTravelproductQuestionsDocument,
    "\n  query fetchTravelproductForDetail($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      price\n      contents\n      images\n      tags\n      pickedCount\n      travelproductAddress {\n        address\n        addressDetail\n        lat\n        lng\n      }\n      buyer {\n        _id\n        name\n        email\n      }\n      seller {\n        _id\n        name\n        email\n      }\n    }\n  }\n": types.FetchTravelproductForDetailDocument,
    "\n  query fetchUserLoggedIn {\n    fetchUserLoggedIn {\n      _id\n      email\n      name\n      userPoint {\n        _id\n        amount\n      }\n    }\n  }\n": types.FetchUserLoggedInDocument,
    "\n  mutation deleteTravelproductQuestion($travelproductQuestionId: ID!) {\n    deleteTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n    )\n  }\n": types.DeleteTravelproductQuestionDocument,
    "\n  mutation updateTravelproductQuestion(\n    $travelproductQuestionId: ID!\n    $updateTravelproductQuestionInput: UpdateTravelproductQuestionInput!\n  ) {\n    updateTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n      updateTravelproductQuestionInput: $updateTravelproductQuestionInput\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": types.UpdateTravelproductQuestionDocument,
    "\n  mutation toggleTravelproductPick($travelproductId: ID!) {\n    toggleTravelproductPick(travelproductId: $travelproductId)\n  }\n": types.ToggleTravelproductPickDocument,
    "\n  mutation createPointTransactionOfBuyingAndSelling($useritemId: ID!) {\n    createPointTransactionOfBuyingAndSelling(useritemId: $useritemId) {\n      _id\n    }\n  }\n": types.CreatePointTransactionOfBuyingAndSellingDocument,
    "\n  mutation createTravelproduct(\n    $createTravelproductInput: CreateTravelproductInput!\n  ) {\n    createTravelproduct(createTravelproductInput: $createTravelproductInput) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n": types.CreateTravelproductDocument,
    "\n  mutation updateTravelproduct(\n    $updateTravelproductInput: UpdateTravelproductInput!\n    $travelproductId: ID!\n  ) {\n    updateTravelproduct(\n      updateTravelproductInput: $updateTravelproductInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n": types.UpdateTravelproductDocument,
    "\n  mutation uploadTravelproductFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n    }\n  }\n": types.UploadTravelproductFileDocument,
    "\n  query fetchTravelproductForEdit($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n": types.FetchTravelproductForEditDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoardHomework10Detail($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n    }\n  }\n"): (typeof documents)["\n  query fetchBoardHomework10Detail($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoardsHomework10($page: Int) {\n    fetchBoards(page: $page) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query fetchBoardsHomework10($page: Int) {\n    fetchBoards(page: $page) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation deleteBoardHomework10($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n"): (typeof documents)["\n  mutation deleteBoardHomework10($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation loginUser($email: String!, $password: String!) {\n    loginUser(email: $email, password: $password) {\n      accessToken\n    }\n  }\n"): (typeof documents)["\n  mutation loginUser($email: String!, $password: String!) {\n    loginUser(email: $email, password: $password) {\n      accessToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createUser($createUserInput: CreateUserInput!) {\n    createUser(createUserInput: $createUserInput) {\n      _id\n      email\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation createUser($createUserInput: CreateUserInput!) {\n    createUser(createUserInput: $createUserInput) {\n      _id\n      email\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createBoard7(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n"): (typeof documents)["\n  mutation createBoard7(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoardHomework8($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n    }\n  }\n"): (typeof documents)["\n  query fetchBoardHomework8($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createBoard8(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n"): (typeof documents)["\n  mutation createBoard8(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoardHomework9Detail($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n    }\n  }\n"): (typeof documents)["\n  query fetchBoardHomework9Detail($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createBoard9(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n"): (typeof documents)["\n  mutation createBoard9(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoardsHomework9($page: Int) {\n    fetchBoards(page: $page) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query fetchBoardsHomework9($page: Int) {\n    fetchBoards(page: $page) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation deleteBoardHomework9($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n"): (typeof documents)["\n  mutation deleteBoardHomework9($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation restoreAccessToken {\n    restoreAccessToken {\n      accessToken\n    }\n  }\n"): (typeof documents)["\n  mutation restoreAccessToken {\n    restoreAccessToken {\n      accessToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FetchBoardComments($page: Int, $boardId: ID!) {\n    fetchBoardComments(page: $page, boardId: $boardId) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query FetchBoardComments($page: Int, $boardId: ID!) {\n    fetchBoardComments(page: $page, boardId: $boardId) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createBoardComment(\n    $createBoardCommentInput: CreateBoardCommentInput!\n    $boardId: ID!\n  ) {\n    createBoardComment(\n      createBoardCommentInput: $createBoardCommentInput\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  mutation createBoardComment(\n    $createBoardCommentInput: CreateBoardCommentInput!\n    $boardId: ID!\n  ) {\n    createBoardComment(\n      createBoardCommentInput: $createBoardCommentInput\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateBoardComment(\n    $updateBoardCommentInput: UpdateBoardCommentInput!\n    $password: String\n    $boardCommentId: ID!\n  ) {\n    updateBoardComment(\n      updateBoardCommentInput: $updateBoardCommentInput\n      password: $password\n      boardCommentId: $boardCommentId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  mutation updateBoardComment(\n    $updateBoardCommentInput: UpdateBoardCommentInput!\n    $password: String\n    $boardCommentId: ID!\n  ) {\n    updateBoardComment(\n      updateBoardCommentInput: $updateBoardCommentInput\n      password: $password\n      boardCommentId: $boardCommentId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoard($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchBoard($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoardLegacyDetail($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchBoardLegacyDetail($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoards(\n    $page: Int\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoards(\n      page: $page\n      search: $search\n      startDate: $startDate\n      endDate: $endDate\n    ) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query fetchBoards(\n    $page: Int\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoards(\n      page: $page\n      search: $search\n      startDate: $startDate\n      endDate: $endDate\n    ) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation deleteBoard($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n"): (typeof documents)["\n  mutation deleteBoard($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoardsCount(\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoardsCount(search: $search, startDate: $startDate, endDate: $endDate)\n  }\n"): (typeof documents)["\n  query fetchBoardsCount(\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoardsCount(search: $search, startDate: $startDate, endDate: $endDate)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoardsLegacyList($page: Int) {\n    fetchBoards(page: $page) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query fetchBoardsLegacyList($page: Int) {\n    fetchBoards(page: $page) {\n      _id\n      writer\n      title\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation deleteBoardLegacyList($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n"): (typeof documents)["\n  mutation deleteBoardLegacyList($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createBoard(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n    $youtubeUrl: String\n    $boardAddress: BoardAddressInput\n    $images: [String!]\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n        youtubeUrl: $youtubeUrl\n        boardAddress: $boardAddress\n        images: $images\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n      youtubeUrl\n      images\n    }\n  }\n"): (typeof documents)["\n  mutation createBoard(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n    $youtubeUrl: String\n    $boardAddress: BoardAddressInput\n    $images: [String!]\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n        youtubeUrl: $youtubeUrl\n        boardAddress: $boardAddress\n        images: $images\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n      youtubeUrl\n      images\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoardWrite($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchBoardWrite($boardId: ID!) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateBoard(\n    $updateBoardInput: UpdateBoardInput!\n    $password: String\n    $boardId: ID!\n  ) {\n    updateBoard(\n      updateBoardInput: $updateBoardInput\n      password: $password\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n"): (typeof documents)["\n  mutation updateBoard(\n    $updateBoardInput: UpdateBoardInput!\n    $password: String\n    $boardId: ID!\n  ) {\n    updateBoard(\n      updateBoardInput: $updateBoardInput\n      password: $password\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation uploadBoardFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n      _id\n      size\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation uploadBoardFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n      _id\n      size\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createTravelproductQuestionAnswer(\n    $createTravelproductQuestionAnswerInput: CreateTravelproductQuestionAnswerInput!\n    $travelproductQuestionId: ID!\n  ) {\n    createTravelproductQuestionAnswer(\n      createTravelproductQuestionAnswerInput: $createTravelproductQuestionAnswerInput\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation createTravelproductQuestionAnswer(\n    $createTravelproductQuestionAnswerInput: CreateTravelproductQuestionAnswerInput!\n    $travelproductQuestionId: ID!\n  ) {\n    createTravelproductQuestionAnswer(\n      createTravelproductQuestionAnswerInput: $createTravelproductQuestionAnswerInput\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchTravelproductQuestionAnswersForList(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchTravelproductQuestionAnswersForList(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n    $updateTravelproductQuestionAnswerInput: UpdateTravelproductQuestionAnswerInput!\n  ) {\n    updateTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n      updateTravelproductQuestionAnswerInput: $updateTravelproductQuestionAnswerInput\n    ) {\n      _id\n      contents\n    }\n  }\n"): (typeof documents)["\n  mutation updateTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n    $updateTravelproductQuestionAnswerInput: UpdateTravelproductQuestionAnswerInput!\n  ) {\n    updateTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n      updateTravelproductQuestionAnswerInput: $updateTravelproductQuestionAnswerInput\n    ) {\n      _id\n      contents\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchTravelproductQuestionAnswersForReply(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchTravelproductQuestionAnswersForReply(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation deleteTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n  ) {\n    deleteTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n    )\n  }\n"): (typeof documents)["\n  mutation deleteTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n  ) {\n    deleteTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n    )\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createTravelproductQuestion(\n    $createTravelproductQuestionInput: CreateTravelproductQuestionInput!\n    $travelproductId: ID!\n  ) {\n    createTravelproductQuestion(\n      createTravelproductQuestionInput: $createTravelproductQuestionInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation createTravelproductQuestion(\n    $createTravelproductQuestionInput: CreateTravelproductQuestionInput!\n    $travelproductId: ID!\n  ) {\n    createTravelproductQuestion(\n      createTravelproductQuestionInput: $createTravelproductQuestionInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchTravelproductQuestions($page: Int, $travelproductId: ID!) {\n    fetchTravelproductQuestions(\n      page: $page\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchTravelproductQuestions($page: Int, $travelproductId: ID!) {\n    fetchTravelproductQuestions(\n      page: $page\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchTravelproductForDetail($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      price\n      contents\n      images\n      tags\n      pickedCount\n      travelproductAddress {\n        address\n        addressDetail\n        lat\n        lng\n      }\n      buyer {\n        _id\n        name\n        email\n      }\n      seller {\n        _id\n        name\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchTravelproductForDetail($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      price\n      contents\n      images\n      tags\n      pickedCount\n      travelproductAddress {\n        address\n        addressDetail\n        lat\n        lng\n      }\n      buyer {\n        _id\n        name\n        email\n      }\n      seller {\n        _id\n        name\n        email\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchUserLoggedIn {\n    fetchUserLoggedIn {\n      _id\n      email\n      name\n      userPoint {\n        _id\n        amount\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchUserLoggedIn {\n    fetchUserLoggedIn {\n      _id\n      email\n      name\n      userPoint {\n        _id\n        amount\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation deleteTravelproductQuestion($travelproductQuestionId: ID!) {\n    deleteTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n    )\n  }\n"): (typeof documents)["\n  mutation deleteTravelproductQuestion($travelproductQuestionId: ID!) {\n    deleteTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n    )\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateTravelproductQuestion(\n    $travelproductQuestionId: ID!\n    $updateTravelproductQuestionInput: UpdateTravelproductQuestionInput!\n  ) {\n    updateTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n      updateTravelproductQuestionInput: $updateTravelproductQuestionInput\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateTravelproductQuestion(\n    $travelproductQuestionId: ID!\n    $updateTravelproductQuestionInput: UpdateTravelproductQuestionInput!\n  ) {\n    updateTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n      updateTravelproductQuestionInput: $updateTravelproductQuestionInput\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation toggleTravelproductPick($travelproductId: ID!) {\n    toggleTravelproductPick(travelproductId: $travelproductId)\n  }\n"): (typeof documents)["\n  mutation toggleTravelproductPick($travelproductId: ID!) {\n    toggleTravelproductPick(travelproductId: $travelproductId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createPointTransactionOfBuyingAndSelling($useritemId: ID!) {\n    createPointTransactionOfBuyingAndSelling(useritemId: $useritemId) {\n      _id\n    }\n  }\n"): (typeof documents)["\n  mutation createPointTransactionOfBuyingAndSelling($useritemId: ID!) {\n    createPointTransactionOfBuyingAndSelling(useritemId: $useritemId) {\n      _id\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createTravelproduct(\n    $createTravelproductInput: CreateTravelproductInput!\n  ) {\n    createTravelproduct(createTravelproductInput: $createTravelproductInput) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation createTravelproduct(\n    $createTravelproductInput: CreateTravelproductInput!\n  ) {\n    createTravelproduct(createTravelproductInput: $createTravelproductInput) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateTravelproduct(\n    $updateTravelproductInput: UpdateTravelproductInput!\n    $travelproductId: ID!\n  ) {\n    updateTravelproduct(\n      updateTravelproductInput: $updateTravelproductInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateTravelproduct(\n    $updateTravelproductInput: UpdateTravelproductInput!\n    $travelproductId: ID!\n  ) {\n    updateTravelproduct(\n      updateTravelproductInput: $updateTravelproductInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation uploadTravelproductFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n    }\n  }\n"): (typeof documents)["\n  mutation uploadTravelproductFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchTravelproductForEdit($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchTravelproductForEdit($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;