/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation createUser($createUserInput: CreateUserInput!) {\n    createUser(createUserInput: $createUserInput) {\n      _id\n      email\n      name\n    }\n  }\n": typeof types.CreateUserDocument,
    "\n  fragment BoardAddressSet on Board {\n    boardAddress {\n      _id\n      zipcode\n      address\n      addressDetail\n    }\n  }\n": typeof types.BoardAddressSetFragmentDoc,
    "\n  fragment BoardsItemSet on Board {\n    _id\n    writer\n    title\n    createdAt\n    user {\n      _id\n    }\n  }\n": typeof types.BoardsItemSetFragmentDoc,
    "\n  fragment TravelProductTravelSet on Travelproduct {\n    _id\n  }\n": typeof types.TravelProductTravelSetFragmentDoc,
    "\n  fragment TravelProductUserSet on User {\n    _id\n    name\n    email\n  }\n": typeof types.TravelProductUserSetFragmentDoc,
    "\n  mutation restoreAccessToken {\n    restoreAccessToken {\n      accessToken\n    }\n  }\n": typeof types.RestoreAccessTokenDocument,
    "\n  query FetchBoardComments($page: Int, $boardId: ID!) {\n    fetchBoardComments(page: $page, boardId: $boardId) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n": typeof types.FetchBoardCommentsDocument,
    "\n  mutation createBoardComment(\n    $createBoardCommentInput: CreateBoardCommentInput!\n    $boardId: ID!\n  ) {\n    createBoardComment(\n      createBoardCommentInput: $createBoardCommentInput\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n": typeof types.CreateBoardCommentDocument,
    "\n  mutation updateBoardComment(\n    $updateBoardCommentInput: UpdateBoardCommentInput!\n    $password: String\n    $boardCommentId: ID!\n  ) {\n    updateBoardComment(\n      updateBoardCommentInput: $updateBoardCommentInput\n      password: $password\n      boardCommentId: $boardCommentId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n": typeof types.UpdateBoardCommentDocument,
    "\n  \n  query fetchBoard($boardId: ID!, $isIncludeBoardAddress: Boolean = false) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      ...BoardAddressSet @include(if: $isIncludeBoardAddress)\n    }\n  }\n": typeof types.FetchBoardDocument,
    "\n  mutation likeBoard($boardId: ID!) {\n    likeBoard(boardId: $boardId)\n  }\n": typeof types.LikeBoardDocument,
    "\n  mutation dislikeBoard($boardId: ID!) {\n    dislikeBoard(boardId: $boardId)\n  }\n": typeof types.DislikeBoardDocument,
    "\n  query fetchBoardsOfTheBest {\n    fetchBoardsOfTheBest {\n      _id\n      writer\n      title\n      contents\n      images\n      likeCount\n      createdAt\n      user {\n        _id\n        name\n      }\n    }\n  }\n": typeof types.FetchBoardsOfTheBestDocument,
    "\n  \n  query fetchBoards(\n    $page: Int\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoards(\n      page: $page\n      search: $search\n      startDate: $startDate\n      endDate: $endDate\n    ) {\n      ...BoardsItemSet\n    }\n  }\n": typeof types.FetchBoardsDocument,
    "\n  mutation deleteBoard($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n": typeof types.DeleteBoardDocument,
    "\n  query fetchBoardsCount(\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoardsCount(search: $search, startDate: $startDate, endDate: $endDate)\n  }\n": typeof types.FetchBoardsCountDocument,
    "\n  mutation createBoard(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n    $youtubeUrl: String\n    $boardAddress: BoardAddressInput\n    $images: [String!]\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n        youtubeUrl: $youtubeUrl\n        boardAddress: $boardAddress\n        images: $images\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n      youtubeUrl\n      images\n    }\n  }\n": typeof types.CreateBoardDocument,
    "\n  \n  query fetchBoardWrite(\n    $boardId: ID!\n    $isIncludeBoardAddress: Boolean = false\n  ) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      ...BoardAddressSet @include(if: $isIncludeBoardAddress)\n    }\n  }\n": typeof types.FetchBoardWriteDocument,
    "\n  mutation updateBoard(\n    $updateBoardInput: UpdateBoardInput!\n    $password: String\n    $boardId: ID!\n  ) {\n    updateBoard(\n      updateBoardInput: $updateBoardInput\n      password: $password\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n": typeof types.UpdateBoardDocument,
    "\n  mutation uploadBoardFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n      _id\n      size\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UploadBoardFileDocument,
    "\n  mutation loginUser($email: String!, $password: String!) {\n    loginUser(email: $email, password: $password) {\n      accessToken\n    }\n  }\n": typeof types.LoginUserDocument,
    "\n  query mypageFetchUserLoggedIn {\n    fetchUserLoggedIn {\n      _id\n      email\n      name\n      userPoint {\n        _id\n        amount\n      }\n    }\n  }\n": typeof types.MypageFetchUserLoggedInDocument,
    "\n  query mypageFetchPointTransactions($search: String, $page: Int) {\n    fetchPointTransactions(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n      }\n      user {\n        _id\n      }\n    }\n  }\n": typeof types.MypageFetchPointTransactionsDocument,
    "\n  query mypageFetchPointTransactionsOfLoading($search: String, $page: Int) {\n    fetchPointTransactionsOfLoading(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n      }\n      user {\n        _id\n      }\n    }\n  }\n": typeof types.MypageFetchPointTransactionsOfLoadingDocument,
    "\n  query mypageFetchPointTransactionsOfBuying($search: String, $page: Int) {\n    fetchPointTransactionsOfBuying(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n        seller {\n          _id\n        }\n      }\n      user {\n        _id\n      }\n    }\n  }\n": typeof types.MypageFetchPointTransactionsOfBuyingDocument,
    "\n  query mypageFetchPointTransactionsOfSelling($search: String, $page: Int) {\n    fetchPointTransactionsOfSelling(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n      }\n      user {\n        _id\n      }\n    }\n  }\n": typeof types.MypageFetchPointTransactionsOfSellingDocument,
    "\n  query myPageFetchTravelproductsISold($search: String, $page: Int) {\n    fetchTravelproductsISold(search: $search, page: $page) {\n      _id\n      name\n      price\n      createdAt\n      soldAt\n      buyer {\n        _id\n        name\n      }\n      seller {\n        _id\n        name\n      }\n    }\n  }\n": typeof types.MyPageFetchTravelproductsISoldDocument,
    "\n  query myPageFetchTravelproductsIPicked($search: String, $page: Int) {\n    fetchTravelproductsIPicked(search: $search, page: $page) {\n      _id\n      name\n      price\n      createdAt\n      soldAt\n      buyer {\n        _id\n        name\n      }\n      seller {\n        _id\n        name\n      }\n    }\n  }\n": typeof types.MyPageFetchTravelproductsIPickedDocument,
    "\n  query myPageFetchTravelproductsCountISold {\n    fetchTravelproductsCountISold\n  }\n": typeof types.MyPageFetchTravelproductsCountISoldDocument,
    "\n  query myPageFetchTravelproductsCountIPicked {\n    fetchTravelproductsCountIPicked\n  }\n": typeof types.MyPageFetchTravelproductsCountIPickedDocument,
    "\n  mutation myPageDeleteTravelproduct($travelproductId: ID!) {\n    deleteTravelproduct(travelproductId: $travelproductId)\n  }\n": typeof types.MyPageDeleteTravelproductDocument,
    "\n  mutation createTravelproductQuestionAnswer(\n    $createTravelproductQuestionAnswerInput: CreateTravelproductQuestionAnswerInput!\n    $travelproductQuestionId: ID!\n  ) {\n    createTravelproductQuestionAnswer(\n      createTravelproductQuestionAnswerInput: $createTravelproductQuestionAnswerInput\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": typeof types.CreateTravelproductQuestionAnswerDocument,
    "\n  query fetchTravelproductQuestionAnswersForList(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": typeof types.FetchTravelproductQuestionAnswersForListDocument,
    "\n  mutation updateTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n    $updateTravelproductQuestionAnswerInput: UpdateTravelproductQuestionAnswerInput!\n  ) {\n    updateTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n      updateTravelproductQuestionAnswerInput: $updateTravelproductQuestionAnswerInput\n    ) {\n      _id\n      contents\n    }\n  }\n": typeof types.UpdateTravelproductQuestionAnswerDocument,
    "\n  query fetchTravelproductQuestionAnswersForReply(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": typeof types.FetchTravelproductQuestionAnswersForReplyDocument,
    "\n  mutation deleteTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n  ) {\n    deleteTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n    )\n  }\n": typeof types.DeleteTravelproductQuestionAnswerDocument,
    "\n    query FetchTravelProduct($travelproductId: ID!) {\n      fetchTravelproduct(travelproductId: $travelproductId) {\n        _id\n        name\n        contents\n        images\n      }\n    }\n  ": typeof types.FetchTravelProductDocument,
    "\n  \n  \n  mutation createTravelproductQuestion(\n    $createTravelproductQuestionInput: CreateTravelproductQuestionInput!\n    $travelproductId: ID!\n  ) {\n    createTravelproductQuestion(\n      createTravelproductQuestionInput: $createTravelproductQuestionInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      createdAt\n      updatedAt\n      travelproduct {\n        ...TravelProductTravelSet\n      }\n      user {\n        ...TravelProductUserSet\n      }\n    }\n  }\n": typeof types.CreateTravelproductQuestionDocument,
    "\n  \n  \n  query fetchTravelproductQuestions($page: Int, $travelproductId: ID!) {\n    fetchTravelproductQuestions(\n      page: $page\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      createdAt\n      updatedAt\n      travelproduct {\n        ...TravelProductTravelSet\n      }\n      user {\n        ...TravelProductUserSet\n      }\n    }\n  }\n": typeof types.FetchTravelproductQuestionsDocument,
    "\n  query fetchTravelproductForDetail($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      price\n      contents\n      images\n      tags\n      pickedCount\n      travelproductAddress {\n        address\n        addressDetail\n        lat\n        lng\n        zipcode\n      }\n      buyer {\n        _id\n        name\n        email\n      }\n      seller {\n        _id\n        name\n        email\n      }\n    }\n  }\n": typeof types.FetchTravelproductForDetailDocument,
    "\n  query fetchUserLoggedIn {\n    fetchUserLoggedIn {\n      _id\n      email\n      name\n      userPoint {\n        _id\n        amount\n      }\n    }\n  }\n": typeof types.FetchUserLoggedInDocument,
    "\n  mutation deleteTravelproductQuestion($travelproductQuestionId: ID!) {\n    deleteTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n    )\n  }\n": typeof types.DeleteTravelproductQuestionDocument,
    "\n  mutation updateTravelproductQuestion(\n    $travelproductQuestionId: ID!\n    $updateTravelproductQuestionInput: UpdateTravelproductQuestionInput!\n  ) {\n    updateTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n      updateTravelproductQuestionInput: $updateTravelproductQuestionInput\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": typeof types.UpdateTravelproductQuestionDocument,
    "\n  mutation toggleTravelproductPick($travelproductId: ID!) {\n    toggleTravelproductPick(travelproductId: $travelproductId)\n  }\n": typeof types.ToggleTravelproductPickDocument,
    "\n  mutation createPointTransactionOfBuyingAndSelling($useritemId: ID!) {\n    createPointTransactionOfBuyingAndSelling(useritemId: $useritemId) {\n      _id\n    }\n  }\n": typeof types.CreatePointTransactionOfBuyingAndSellingDocument,
    "\n  mutation createPointTransactionOfLoading($paymentId: ID!) {\n    createPointTransactionOfLoading(paymentId: $paymentId) {\n      _id\n    }\n  }\n": typeof types.CreatePointTransactionOfLoadingDocument,
    "\n  query fetchTravelproductsIPicked($search: String, $page: Int) {\n    fetchTravelproductsIPicked(search: $search, page: $page) {\n      _id\n    }\n  }\n": typeof types.FetchTravelproductsIPickedDocument,
    "\n  mutation createTravelproduct(\n    $createTravelproductInput: CreateTravelproductInput!\n  ) {\n    createTravelproduct(createTravelproductInput: $createTravelproductInput) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n": typeof types.CreateTravelproductDocument,
    "\n  mutation updateTravelproduct(\n    $updateTravelproductInput: UpdateTravelproductInput!\n    $travelproductId: ID!\n  ) {\n    updateTravelproduct(\n      updateTravelproductInput: $updateTravelproductInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n": typeof types.UpdateTravelproductDocument,
    "\n  mutation uploadTravelproductFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n    }\n  }\n": typeof types.UploadTravelproductFileDocument,
    "\n  query fetchTravelproductForEdit($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n": typeof types.FetchTravelproductForEditDocument,
};
const documents: Documents = {
    "\n  mutation createUser($createUserInput: CreateUserInput!) {\n    createUser(createUserInput: $createUserInput) {\n      _id\n      email\n      name\n    }\n  }\n": types.CreateUserDocument,
    "\n  fragment BoardAddressSet on Board {\n    boardAddress {\n      _id\n      zipcode\n      address\n      addressDetail\n    }\n  }\n": types.BoardAddressSetFragmentDoc,
    "\n  fragment BoardsItemSet on Board {\n    _id\n    writer\n    title\n    createdAt\n    user {\n      _id\n    }\n  }\n": types.BoardsItemSetFragmentDoc,
    "\n  fragment TravelProductTravelSet on Travelproduct {\n    _id\n  }\n": types.TravelProductTravelSetFragmentDoc,
    "\n  fragment TravelProductUserSet on User {\n    _id\n    name\n    email\n  }\n": types.TravelProductUserSetFragmentDoc,
    "\n  mutation restoreAccessToken {\n    restoreAccessToken {\n      accessToken\n    }\n  }\n": types.RestoreAccessTokenDocument,
    "\n  query FetchBoardComments($page: Int, $boardId: ID!) {\n    fetchBoardComments(page: $page, boardId: $boardId) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n": types.FetchBoardCommentsDocument,
    "\n  mutation createBoardComment(\n    $createBoardCommentInput: CreateBoardCommentInput!\n    $boardId: ID!\n  ) {\n    createBoardComment(\n      createBoardCommentInput: $createBoardCommentInput\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n": types.CreateBoardCommentDocument,
    "\n  mutation updateBoardComment(\n    $updateBoardCommentInput: UpdateBoardCommentInput!\n    $password: String\n    $boardCommentId: ID!\n  ) {\n    updateBoardComment(\n      updateBoardCommentInput: $updateBoardCommentInput\n      password: $password\n      boardCommentId: $boardCommentId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n": types.UpdateBoardCommentDocument,
    "\n  \n  query fetchBoard($boardId: ID!, $isIncludeBoardAddress: Boolean = false) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      ...BoardAddressSet @include(if: $isIncludeBoardAddress)\n    }\n  }\n": types.FetchBoardDocument,
    "\n  mutation likeBoard($boardId: ID!) {\n    likeBoard(boardId: $boardId)\n  }\n": types.LikeBoardDocument,
    "\n  mutation dislikeBoard($boardId: ID!) {\n    dislikeBoard(boardId: $boardId)\n  }\n": types.DislikeBoardDocument,
    "\n  query fetchBoardsOfTheBest {\n    fetchBoardsOfTheBest {\n      _id\n      writer\n      title\n      contents\n      images\n      likeCount\n      createdAt\n      user {\n        _id\n        name\n      }\n    }\n  }\n": types.FetchBoardsOfTheBestDocument,
    "\n  \n  query fetchBoards(\n    $page: Int\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoards(\n      page: $page\n      search: $search\n      startDate: $startDate\n      endDate: $endDate\n    ) {\n      ...BoardsItemSet\n    }\n  }\n": types.FetchBoardsDocument,
    "\n  mutation deleteBoard($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n": types.DeleteBoardDocument,
    "\n  query fetchBoardsCount(\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoardsCount(search: $search, startDate: $startDate, endDate: $endDate)\n  }\n": types.FetchBoardsCountDocument,
    "\n  mutation createBoard(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n    $youtubeUrl: String\n    $boardAddress: BoardAddressInput\n    $images: [String!]\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n        youtubeUrl: $youtubeUrl\n        boardAddress: $boardAddress\n        images: $images\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n      youtubeUrl\n      images\n    }\n  }\n": types.CreateBoardDocument,
    "\n  \n  query fetchBoardWrite(\n    $boardId: ID!\n    $isIncludeBoardAddress: Boolean = false\n  ) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      ...BoardAddressSet @include(if: $isIncludeBoardAddress)\n    }\n  }\n": types.FetchBoardWriteDocument,
    "\n  mutation updateBoard(\n    $updateBoardInput: UpdateBoardInput!\n    $password: String\n    $boardId: ID!\n  ) {\n    updateBoard(\n      updateBoardInput: $updateBoardInput\n      password: $password\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n": types.UpdateBoardDocument,
    "\n  mutation uploadBoardFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n      _id\n      size\n      createdAt\n      updatedAt\n    }\n  }\n": types.UploadBoardFileDocument,
    "\n  mutation loginUser($email: String!, $password: String!) {\n    loginUser(email: $email, password: $password) {\n      accessToken\n    }\n  }\n": types.LoginUserDocument,
    "\n  query mypageFetchUserLoggedIn {\n    fetchUserLoggedIn {\n      _id\n      email\n      name\n      userPoint {\n        _id\n        amount\n      }\n    }\n  }\n": types.MypageFetchUserLoggedInDocument,
    "\n  query mypageFetchPointTransactions($search: String, $page: Int) {\n    fetchPointTransactions(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n      }\n      user {\n        _id\n      }\n    }\n  }\n": types.MypageFetchPointTransactionsDocument,
    "\n  query mypageFetchPointTransactionsOfLoading($search: String, $page: Int) {\n    fetchPointTransactionsOfLoading(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n      }\n      user {\n        _id\n      }\n    }\n  }\n": types.MypageFetchPointTransactionsOfLoadingDocument,
    "\n  query mypageFetchPointTransactionsOfBuying($search: String, $page: Int) {\n    fetchPointTransactionsOfBuying(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n        seller {\n          _id\n        }\n      }\n      user {\n        _id\n      }\n    }\n  }\n": types.MypageFetchPointTransactionsOfBuyingDocument,
    "\n  query mypageFetchPointTransactionsOfSelling($search: String, $page: Int) {\n    fetchPointTransactionsOfSelling(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n      }\n      user {\n        _id\n      }\n    }\n  }\n": types.MypageFetchPointTransactionsOfSellingDocument,
    "\n  query myPageFetchTravelproductsISold($search: String, $page: Int) {\n    fetchTravelproductsISold(search: $search, page: $page) {\n      _id\n      name\n      price\n      createdAt\n      soldAt\n      buyer {\n        _id\n        name\n      }\n      seller {\n        _id\n        name\n      }\n    }\n  }\n": types.MyPageFetchTravelproductsISoldDocument,
    "\n  query myPageFetchTravelproductsIPicked($search: String, $page: Int) {\n    fetchTravelproductsIPicked(search: $search, page: $page) {\n      _id\n      name\n      price\n      createdAt\n      soldAt\n      buyer {\n        _id\n        name\n      }\n      seller {\n        _id\n        name\n      }\n    }\n  }\n": types.MyPageFetchTravelproductsIPickedDocument,
    "\n  query myPageFetchTravelproductsCountISold {\n    fetchTravelproductsCountISold\n  }\n": types.MyPageFetchTravelproductsCountISoldDocument,
    "\n  query myPageFetchTravelproductsCountIPicked {\n    fetchTravelproductsCountIPicked\n  }\n": types.MyPageFetchTravelproductsCountIPickedDocument,
    "\n  mutation myPageDeleteTravelproduct($travelproductId: ID!) {\n    deleteTravelproduct(travelproductId: $travelproductId)\n  }\n": types.MyPageDeleteTravelproductDocument,
    "\n  mutation createTravelproductQuestionAnswer(\n    $createTravelproductQuestionAnswerInput: CreateTravelproductQuestionAnswerInput!\n    $travelproductQuestionId: ID!\n  ) {\n    createTravelproductQuestionAnswer(\n      createTravelproductQuestionAnswerInput: $createTravelproductQuestionAnswerInput\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": types.CreateTravelproductQuestionAnswerDocument,
    "\n  query fetchTravelproductQuestionAnswersForList(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": types.FetchTravelproductQuestionAnswersForListDocument,
    "\n  mutation updateTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n    $updateTravelproductQuestionAnswerInput: UpdateTravelproductQuestionAnswerInput!\n  ) {\n    updateTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n      updateTravelproductQuestionAnswerInput: $updateTravelproductQuestionAnswerInput\n    ) {\n      _id\n      contents\n    }\n  }\n": types.UpdateTravelproductQuestionAnswerDocument,
    "\n  query fetchTravelproductQuestionAnswersForReply(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": types.FetchTravelproductQuestionAnswersForReplyDocument,
    "\n  mutation deleteTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n  ) {\n    deleteTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n    )\n  }\n": types.DeleteTravelproductQuestionAnswerDocument,
    "\n    query FetchTravelProduct($travelproductId: ID!) {\n      fetchTravelproduct(travelproductId: $travelproductId) {\n        _id\n        name\n        contents\n        images\n      }\n    }\n  ": types.FetchTravelProductDocument,
    "\n  \n  \n  mutation createTravelproductQuestion(\n    $createTravelproductQuestionInput: CreateTravelproductQuestionInput!\n    $travelproductId: ID!\n  ) {\n    createTravelproductQuestion(\n      createTravelproductQuestionInput: $createTravelproductQuestionInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      createdAt\n      updatedAt\n      travelproduct {\n        ...TravelProductTravelSet\n      }\n      user {\n        ...TravelProductUserSet\n      }\n    }\n  }\n": types.CreateTravelproductQuestionDocument,
    "\n  \n  \n  query fetchTravelproductQuestions($page: Int, $travelproductId: ID!) {\n    fetchTravelproductQuestions(\n      page: $page\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      createdAt\n      updatedAt\n      travelproduct {\n        ...TravelProductTravelSet\n      }\n      user {\n        ...TravelProductUserSet\n      }\n    }\n  }\n": types.FetchTravelproductQuestionsDocument,
    "\n  query fetchTravelproductForDetail($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      price\n      contents\n      images\n      tags\n      pickedCount\n      travelproductAddress {\n        address\n        addressDetail\n        lat\n        lng\n        zipcode\n      }\n      buyer {\n        _id\n        name\n        email\n      }\n      seller {\n        _id\n        name\n        email\n      }\n    }\n  }\n": types.FetchTravelproductForDetailDocument,
    "\n  query fetchUserLoggedIn {\n    fetchUserLoggedIn {\n      _id\n      email\n      name\n      userPoint {\n        _id\n        amount\n      }\n    }\n  }\n": types.FetchUserLoggedInDocument,
    "\n  mutation deleteTravelproductQuestion($travelproductQuestionId: ID!) {\n    deleteTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n    )\n  }\n": types.DeleteTravelproductQuestionDocument,
    "\n  mutation updateTravelproductQuestion(\n    $travelproductQuestionId: ID!\n    $updateTravelproductQuestionInput: UpdateTravelproductQuestionInput!\n  ) {\n    updateTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n      updateTravelproductQuestionInput: $updateTravelproductQuestionInput\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n": types.UpdateTravelproductQuestionDocument,
    "\n  mutation toggleTravelproductPick($travelproductId: ID!) {\n    toggleTravelproductPick(travelproductId: $travelproductId)\n  }\n": types.ToggleTravelproductPickDocument,
    "\n  mutation createPointTransactionOfBuyingAndSelling($useritemId: ID!) {\n    createPointTransactionOfBuyingAndSelling(useritemId: $useritemId) {\n      _id\n    }\n  }\n": types.CreatePointTransactionOfBuyingAndSellingDocument,
    "\n  mutation createPointTransactionOfLoading($paymentId: ID!) {\n    createPointTransactionOfLoading(paymentId: $paymentId) {\n      _id\n    }\n  }\n": types.CreatePointTransactionOfLoadingDocument,
    "\n  query fetchTravelproductsIPicked($search: String, $page: Int) {\n    fetchTravelproductsIPicked(search: $search, page: $page) {\n      _id\n    }\n  }\n": types.FetchTravelproductsIPickedDocument,
    "\n  mutation createTravelproduct(\n    $createTravelproductInput: CreateTravelproductInput!\n  ) {\n    createTravelproduct(createTravelproductInput: $createTravelproductInput) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n": types.CreateTravelproductDocument,
    "\n  mutation updateTravelproduct(\n    $updateTravelproductInput: UpdateTravelproductInput!\n    $travelproductId: ID!\n  ) {\n    updateTravelproduct(\n      updateTravelproductInput: $updateTravelproductInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n": types.UpdateTravelproductDocument,
    "\n  mutation uploadTravelproductFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n    }\n  }\n": types.UploadTravelproductFileDocument,
    "\n  query fetchTravelproductForEdit($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n": types.FetchTravelproductForEditDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createUser($createUserInput: CreateUserInput!) {\n    createUser(createUserInput: $createUserInput) {\n      _id\n      email\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation createUser($createUserInput: CreateUserInput!) {\n    createUser(createUserInput: $createUserInput) {\n      _id\n      email\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment BoardAddressSet on Board {\n    boardAddress {\n      _id\n      zipcode\n      address\n      addressDetail\n    }\n  }\n"): (typeof documents)["\n  fragment BoardAddressSet on Board {\n    boardAddress {\n      _id\n      zipcode\n      address\n      addressDetail\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment BoardsItemSet on Board {\n    _id\n    writer\n    title\n    createdAt\n    user {\n      _id\n    }\n  }\n"): (typeof documents)["\n  fragment BoardsItemSet on Board {\n    _id\n    writer\n    title\n    createdAt\n    user {\n      _id\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment TravelProductTravelSet on Travelproduct {\n    _id\n  }\n"): (typeof documents)["\n  fragment TravelProductTravelSet on Travelproduct {\n    _id\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment TravelProductUserSet on User {\n    _id\n    name\n    email\n  }\n"): (typeof documents)["\n  fragment TravelProductUserSet on User {\n    _id\n    name\n    email\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation restoreAccessToken {\n    restoreAccessToken {\n      accessToken\n    }\n  }\n"): (typeof documents)["\n  mutation restoreAccessToken {\n    restoreAccessToken {\n      accessToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query FetchBoardComments($page: Int, $boardId: ID!) {\n    fetchBoardComments(page: $page, boardId: $boardId) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query FetchBoardComments($page: Int, $boardId: ID!) {\n    fetchBoardComments(page: $page, boardId: $boardId) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createBoardComment(\n    $createBoardCommentInput: CreateBoardCommentInput!\n    $boardId: ID!\n  ) {\n    createBoardComment(\n      createBoardCommentInput: $createBoardCommentInput\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  mutation createBoardComment(\n    $createBoardCommentInput: CreateBoardCommentInput!\n    $boardId: ID!\n  ) {\n    createBoardComment(\n      createBoardCommentInput: $createBoardCommentInput\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateBoardComment(\n    $updateBoardCommentInput: UpdateBoardCommentInput!\n    $password: String\n    $boardCommentId: ID!\n  ) {\n    updateBoardComment(\n      updateBoardCommentInput: $updateBoardCommentInput\n      password: $password\n      boardCommentId: $boardCommentId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  mutation updateBoardComment(\n    $updateBoardCommentInput: UpdateBoardCommentInput!\n    $password: String\n    $boardCommentId: ID!\n  ) {\n    updateBoardComment(\n      updateBoardCommentInput: $updateBoardCommentInput\n      password: $password\n      boardCommentId: $boardCommentId\n    ) {\n      _id\n      writer\n      contents\n      rating\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  \n  query fetchBoard($boardId: ID!, $isIncludeBoardAddress: Boolean = false) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      ...BoardAddressSet @include(if: $isIncludeBoardAddress)\n    }\n  }\n"): (typeof documents)["\n  \n  query fetchBoard($boardId: ID!, $isIncludeBoardAddress: Boolean = false) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      ...BoardAddressSet @include(if: $isIncludeBoardAddress)\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation likeBoard($boardId: ID!) {\n    likeBoard(boardId: $boardId)\n  }\n"): (typeof documents)["\n  mutation likeBoard($boardId: ID!) {\n    likeBoard(boardId: $boardId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation dislikeBoard($boardId: ID!) {\n    dislikeBoard(boardId: $boardId)\n  }\n"): (typeof documents)["\n  mutation dislikeBoard($boardId: ID!) {\n    dislikeBoard(boardId: $boardId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoardsOfTheBest {\n    fetchBoardsOfTheBest {\n      _id\n      writer\n      title\n      contents\n      images\n      likeCount\n      createdAt\n      user {\n        _id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchBoardsOfTheBest {\n    fetchBoardsOfTheBest {\n      _id\n      writer\n      title\n      contents\n      images\n      likeCount\n      createdAt\n      user {\n        _id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  \n  query fetchBoards(\n    $page: Int\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoards(\n      page: $page\n      search: $search\n      startDate: $startDate\n      endDate: $endDate\n    ) {\n      ...BoardsItemSet\n    }\n  }\n"): (typeof documents)["\n  \n  query fetchBoards(\n    $page: Int\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoards(\n      page: $page\n      search: $search\n      startDate: $startDate\n      endDate: $endDate\n    ) {\n      ...BoardsItemSet\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation deleteBoard($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n"): (typeof documents)["\n  mutation deleteBoard($boardId: ID!) {\n    deleteBoard(boardId: $boardId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchBoardsCount(\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoardsCount(search: $search, startDate: $startDate, endDate: $endDate)\n  }\n"): (typeof documents)["\n  query fetchBoardsCount(\n    $search: String\n    $startDate: DateTime\n    $endDate: DateTime\n  ) {\n    fetchBoardsCount(search: $search, startDate: $startDate, endDate: $endDate)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createBoard(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n    $youtubeUrl: String\n    $boardAddress: BoardAddressInput\n    $images: [String!]\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n        youtubeUrl: $youtubeUrl\n        boardAddress: $boardAddress\n        images: $images\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n      youtubeUrl\n      images\n    }\n  }\n"): (typeof documents)["\n  mutation createBoard(\n    $writer: String\n    $password: String\n    $title: String!\n    $contents: String!\n    $youtubeUrl: String\n    $boardAddress: BoardAddressInput\n    $images: [String!]\n  ) {\n    createBoard(\n      createBoardInput: {\n        writer: $writer\n        password: $password\n        title: $title\n        contents: $contents\n        youtubeUrl: $youtubeUrl\n        boardAddress: $boardAddress\n        images: $images\n      }\n    ) {\n      _id\n      writer\n      title\n      contents\n      boardAddress {\n        _id\n        zipcode\n        address\n        addressDetail\n      }\n      youtubeUrl\n      images\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  \n  query fetchBoardWrite(\n    $boardId: ID!\n    $isIncludeBoardAddress: Boolean = false\n  ) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      ...BoardAddressSet @include(if: $isIncludeBoardAddress)\n    }\n  }\n"): (typeof documents)["\n  \n  query fetchBoardWrite(\n    $boardId: ID!\n    $isIncludeBoardAddress: Boolean = false\n  ) {\n    fetchBoard(boardId: $boardId) {\n      _id\n      writer\n      title\n      contents\n      createdAt\n      likeCount\n      dislikeCount\n      images\n      youtubeUrl\n      ...BoardAddressSet @include(if: $isIncludeBoardAddress)\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateBoard(\n    $updateBoardInput: UpdateBoardInput!\n    $password: String\n    $boardId: ID!\n  ) {\n    updateBoard(\n      updateBoardInput: $updateBoardInput\n      password: $password\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n"): (typeof documents)["\n  mutation updateBoard(\n    $updateBoardInput: UpdateBoardInput!\n    $password: String\n    $boardId: ID!\n  ) {\n    updateBoard(\n      updateBoardInput: $updateBoardInput\n      password: $password\n      boardId: $boardId\n    ) {\n      _id\n      writer\n      title\n      contents\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation uploadBoardFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n      _id\n      size\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation uploadBoardFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n      _id\n      size\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation loginUser($email: String!, $password: String!) {\n    loginUser(email: $email, password: $password) {\n      accessToken\n    }\n  }\n"): (typeof documents)["\n  mutation loginUser($email: String!, $password: String!) {\n    loginUser(email: $email, password: $password) {\n      accessToken\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query mypageFetchUserLoggedIn {\n    fetchUserLoggedIn {\n      _id\n      email\n      name\n      userPoint {\n        _id\n        amount\n      }\n    }\n  }\n"): (typeof documents)["\n  query mypageFetchUserLoggedIn {\n    fetchUserLoggedIn {\n      _id\n      email\n      name\n      userPoint {\n        _id\n        amount\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query mypageFetchPointTransactions($search: String, $page: Int) {\n    fetchPointTransactions(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n      }\n      user {\n        _id\n      }\n    }\n  }\n"): (typeof documents)["\n  query mypageFetchPointTransactions($search: String, $page: Int) {\n    fetchPointTransactions(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n      }\n      user {\n        _id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query mypageFetchPointTransactionsOfLoading($search: String, $page: Int) {\n    fetchPointTransactionsOfLoading(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n      }\n      user {\n        _id\n      }\n    }\n  }\n"): (typeof documents)["\n  query mypageFetchPointTransactionsOfLoading($search: String, $page: Int) {\n    fetchPointTransactionsOfLoading(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n      }\n      user {\n        _id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query mypageFetchPointTransactionsOfBuying($search: String, $page: Int) {\n    fetchPointTransactionsOfBuying(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n        seller {\n          _id\n        }\n      }\n      user {\n        _id\n      }\n    }\n  }\n"): (typeof documents)["\n  query mypageFetchPointTransactionsOfBuying($search: String, $page: Int) {\n    fetchPointTransactionsOfBuying(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n        seller {\n          _id\n        }\n      }\n      user {\n        _id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query mypageFetchPointTransactionsOfSelling($search: String, $page: Int) {\n    fetchPointTransactionsOfSelling(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n      }\n      user {\n        _id\n      }\n    }\n  }\n"): (typeof documents)["\n  query mypageFetchPointTransactionsOfSelling($search: String, $page: Int) {\n    fetchPointTransactionsOfSelling(search: $search, page: $page) {\n      _id\n      impUid\n      amount\n      balance\n      status\n      statusDetail\n      createdAt\n      travelproduct {\n        _id\n        name\n      }\n      user {\n        _id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query myPageFetchTravelproductsISold($search: String, $page: Int) {\n    fetchTravelproductsISold(search: $search, page: $page) {\n      _id\n      name\n      price\n      createdAt\n      soldAt\n      buyer {\n        _id\n        name\n      }\n      seller {\n        _id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query myPageFetchTravelproductsISold($search: String, $page: Int) {\n    fetchTravelproductsISold(search: $search, page: $page) {\n      _id\n      name\n      price\n      createdAt\n      soldAt\n      buyer {\n        _id\n        name\n      }\n      seller {\n        _id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query myPageFetchTravelproductsIPicked($search: String, $page: Int) {\n    fetchTravelproductsIPicked(search: $search, page: $page) {\n      _id\n      name\n      price\n      createdAt\n      soldAt\n      buyer {\n        _id\n        name\n      }\n      seller {\n        _id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query myPageFetchTravelproductsIPicked($search: String, $page: Int) {\n    fetchTravelproductsIPicked(search: $search, page: $page) {\n      _id\n      name\n      price\n      createdAt\n      soldAt\n      buyer {\n        _id\n        name\n      }\n      seller {\n        _id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query myPageFetchTravelproductsCountISold {\n    fetchTravelproductsCountISold\n  }\n"): (typeof documents)["\n  query myPageFetchTravelproductsCountISold {\n    fetchTravelproductsCountISold\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query myPageFetchTravelproductsCountIPicked {\n    fetchTravelproductsCountIPicked\n  }\n"): (typeof documents)["\n  query myPageFetchTravelproductsCountIPicked {\n    fetchTravelproductsCountIPicked\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation myPageDeleteTravelproduct($travelproductId: ID!) {\n    deleteTravelproduct(travelproductId: $travelproductId)\n  }\n"): (typeof documents)["\n  mutation myPageDeleteTravelproduct($travelproductId: ID!) {\n    deleteTravelproduct(travelproductId: $travelproductId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createTravelproductQuestionAnswer(\n    $createTravelproductQuestionAnswerInput: CreateTravelproductQuestionAnswerInput!\n    $travelproductQuestionId: ID!\n  ) {\n    createTravelproductQuestionAnswer(\n      createTravelproductQuestionAnswerInput: $createTravelproductQuestionAnswerInput\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation createTravelproductQuestionAnswer(\n    $createTravelproductQuestionAnswerInput: CreateTravelproductQuestionAnswerInput!\n    $travelproductQuestionId: ID!\n  ) {\n    createTravelproductQuestionAnswer(\n      createTravelproductQuestionAnswerInput: $createTravelproductQuestionAnswerInput\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchTravelproductQuestionAnswersForList(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchTravelproductQuestionAnswersForList(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n    $updateTravelproductQuestionAnswerInput: UpdateTravelproductQuestionAnswerInput!\n  ) {\n    updateTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n      updateTravelproductQuestionAnswerInput: $updateTravelproductQuestionAnswerInput\n    ) {\n      _id\n      contents\n    }\n  }\n"): (typeof documents)["\n  mutation updateTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n    $updateTravelproductQuestionAnswerInput: UpdateTravelproductQuestionAnswerInput!\n  ) {\n    updateTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n      updateTravelproductQuestionAnswerInput: $updateTravelproductQuestionAnswerInput\n    ) {\n      _id\n      contents\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchTravelproductQuestionAnswersForReply(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchTravelproductQuestionAnswersForReply(\n    $page: Int\n    $travelproductQuestionId: ID!\n  ) {\n    fetchTravelproductQuestionAnswers(\n      page: $page\n      travelproductQuestionId: $travelproductQuestionId\n    ) {\n      _id\n      contents\n      travelproductQuestion {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation deleteTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n  ) {\n    deleteTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n    )\n  }\n"): (typeof documents)["\n  mutation deleteTravelproductQuestionAnswer(\n    $travelproductQuestionAnswerId: ID!\n  ) {\n    deleteTravelproductQuestionAnswer(\n      travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n    )\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query FetchTravelProduct($travelproductId: ID!) {\n      fetchTravelproduct(travelproductId: $travelproductId) {\n        _id\n        name\n        contents\n        images\n      }\n    }\n  "): (typeof documents)["\n    query FetchTravelProduct($travelproductId: ID!) {\n      fetchTravelproduct(travelproductId: $travelproductId) {\n        _id\n        name\n        contents\n        images\n      }\n    }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  \n  \n  mutation createTravelproductQuestion(\n    $createTravelproductQuestionInput: CreateTravelproductQuestionInput!\n    $travelproductId: ID!\n  ) {\n    createTravelproductQuestion(\n      createTravelproductQuestionInput: $createTravelproductQuestionInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      createdAt\n      updatedAt\n      travelproduct {\n        ...TravelProductTravelSet\n      }\n      user {\n        ...TravelProductUserSet\n      }\n    }\n  }\n"): (typeof documents)["\n  \n  \n  mutation createTravelproductQuestion(\n    $createTravelproductQuestionInput: CreateTravelproductQuestionInput!\n    $travelproductId: ID!\n  ) {\n    createTravelproductQuestion(\n      createTravelproductQuestionInput: $createTravelproductQuestionInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      createdAt\n      updatedAt\n      travelproduct {\n        ...TravelProductTravelSet\n      }\n      user {\n        ...TravelProductUserSet\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  \n  \n  query fetchTravelproductQuestions($page: Int, $travelproductId: ID!) {\n    fetchTravelproductQuestions(\n      page: $page\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      createdAt\n      updatedAt\n      travelproduct {\n        ...TravelProductTravelSet\n      }\n      user {\n        ...TravelProductUserSet\n      }\n    }\n  }\n"): (typeof documents)["\n  \n  \n  query fetchTravelproductQuestions($page: Int, $travelproductId: ID!) {\n    fetchTravelproductQuestions(\n      page: $page\n      travelproductId: $travelproductId\n    ) {\n      _id\n      contents\n      createdAt\n      updatedAt\n      travelproduct {\n        ...TravelProductTravelSet\n      }\n      user {\n        ...TravelProductUserSet\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchTravelproductForDetail($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      price\n      contents\n      images\n      tags\n      pickedCount\n      travelproductAddress {\n        address\n        addressDetail\n        lat\n        lng\n        zipcode\n      }\n      buyer {\n        _id\n        name\n        email\n      }\n      seller {\n        _id\n        name\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchTravelproductForDetail($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      price\n      contents\n      images\n      tags\n      pickedCount\n      travelproductAddress {\n        address\n        addressDetail\n        lat\n        lng\n        zipcode\n      }\n      buyer {\n        _id\n        name\n        email\n      }\n      seller {\n        _id\n        name\n        email\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchUserLoggedIn {\n    fetchUserLoggedIn {\n      _id\n      email\n      name\n      userPoint {\n        _id\n        amount\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchUserLoggedIn {\n    fetchUserLoggedIn {\n      _id\n      email\n      name\n      userPoint {\n        _id\n        amount\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation deleteTravelproductQuestion($travelproductQuestionId: ID!) {\n    deleteTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n    )\n  }\n"): (typeof documents)["\n  mutation deleteTravelproductQuestion($travelproductQuestionId: ID!) {\n    deleteTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n    )\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateTravelproductQuestion(\n    $travelproductQuestionId: ID!\n    $updateTravelproductQuestionInput: UpdateTravelproductQuestionInput!\n  ) {\n    updateTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n      updateTravelproductQuestionInput: $updateTravelproductQuestionInput\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateTravelproductQuestion(\n    $travelproductQuestionId: ID!\n    $updateTravelproductQuestionInput: UpdateTravelproductQuestionInput!\n  ) {\n    updateTravelproductQuestion(\n      travelproductQuestionId: $travelproductQuestionId\n      updateTravelproductQuestionInput: $updateTravelproductQuestionInput\n    ) {\n      _id\n      contents\n      travelproduct {\n        _id\n      }\n      createdAt\n      updatedAt\n      user {\n        _id\n        name\n        email\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation toggleTravelproductPick($travelproductId: ID!) {\n    toggleTravelproductPick(travelproductId: $travelproductId)\n  }\n"): (typeof documents)["\n  mutation toggleTravelproductPick($travelproductId: ID!) {\n    toggleTravelproductPick(travelproductId: $travelproductId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createPointTransactionOfBuyingAndSelling($useritemId: ID!) {\n    createPointTransactionOfBuyingAndSelling(useritemId: $useritemId) {\n      _id\n    }\n  }\n"): (typeof documents)["\n  mutation createPointTransactionOfBuyingAndSelling($useritemId: ID!) {\n    createPointTransactionOfBuyingAndSelling(useritemId: $useritemId) {\n      _id\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createPointTransactionOfLoading($paymentId: ID!) {\n    createPointTransactionOfLoading(paymentId: $paymentId) {\n      _id\n    }\n  }\n"): (typeof documents)["\n  mutation createPointTransactionOfLoading($paymentId: ID!) {\n    createPointTransactionOfLoading(paymentId: $paymentId) {\n      _id\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchTravelproductsIPicked($search: String, $page: Int) {\n    fetchTravelproductsIPicked(search: $search, page: $page) {\n      _id\n    }\n  }\n"): (typeof documents)["\n  query fetchTravelproductsIPicked($search: String, $page: Int) {\n    fetchTravelproductsIPicked(search: $search, page: $page) {\n      _id\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation createTravelproduct(\n    $createTravelproductInput: CreateTravelproductInput!\n  ) {\n    createTravelproduct(createTravelproductInput: $createTravelproductInput) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation createTravelproduct(\n    $createTravelproductInput: CreateTravelproductInput!\n  ) {\n    createTravelproduct(createTravelproductInput: $createTravelproductInput) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation updateTravelproduct(\n    $updateTravelproductInput: UpdateTravelproductInput!\n    $travelproductId: ID!\n  ) {\n    updateTravelproduct(\n      updateTravelproductInput: $updateTravelproductInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation updateTravelproduct(\n    $updateTravelproductInput: UpdateTravelproductInput!\n    $travelproductId: ID!\n  ) {\n    updateTravelproduct(\n      updateTravelproductInput: $updateTravelproductInput\n      travelproductId: $travelproductId\n    ) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation uploadTravelproductFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n    }\n  }\n"): (typeof documents)["\n  mutation uploadTravelproductFile($file: Upload!) {\n    uploadFile(file: $file) {\n      url\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query fetchTravelproductForEdit($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n"): (typeof documents)["\n  query fetchTravelproductForEdit($travelproductId: ID!) {\n    fetchTravelproduct(travelproductId: $travelproductId) {\n      _id\n      name\n      remarks\n      contents\n      price\n      tags\n      images\n      travelproductAddress {\n        zipcode\n        address\n        addressDetail\n        lat\n        lng\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;